---
- import_tasks: tasks/README.md.yml
  vars:
    is_meta_package: false

- name: PackageInfo.g PackageName
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "PackageName :="
    line: 'PackageName := "{{ package.name }}",'

- name: PackageInfo.g Subtitle
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "Subtitle :="
    line: 'Subtitle := "{{ package.description }}",'

- name: PackageInfo.g License
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "License :="
    line: 'License := "GPL-2.0-or-later",'
    insertafter: "Date :="

- name: PackageInfo.g Date
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "Date :="
    line: 'Date := Concatenation( "01/", ~.Version{[ 6, 7 ]}, "/", ~.Version{[ 1 .. 4 ]} ),'

- name: PackageInfo.g URLs
  blockinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    marker: "# {mark} URLS"
    block: |
      SourceRepository := rec(
          Type := "git",
          URL := "https://github.com/homalg-project/{{ package.repo }}",
      ),
      IssueTrackerURL := Concatenation( ~.SourceRepository.URL, "/issues" ),
      PackageWWWHome  := "https://homalg-project.github.io/pkg/{{ package.name }}",
      PackageInfoURL  := "https://homalg-project.github.io/{{ package.path }}/PackageInfo.g",
      README_URL      := "https://homalg-project.github.io/{{ package.path }}/README.md",
      {% if meta_package is defined -%}
        ArchiveURL      := Concatenation( "https://github.com/homalg-project/{{ package.repo }}/releases/download/{{ package.name }}-", ~.Version, "/{{ package.name }}-", ~.Version ),
      {% else -%}
        ArchiveURL      := Concatenation( "https://github.com/homalg-project/{{ package.repo }}/releases/download/v", ~.Version, "/{{ package.name }}-", ~.Version ),
      {% endif %}

- name: PackageInfo.g ArchiveFormats
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "ArchiveFormats :="
    line: 'ArchiveFormats := ".tar.gz .zip",'

- name: PackageInfo.g PackageDoc.BookName
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "^  BookName  := "
    line: '  BookName  := "{{ package.name }}",'

- name: PackageInfo.g PackageDoc.LongTitle
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "^  LongTitle := "
    line: '  LongTitle := "{{ package.description }}",'
  when: not package.docu_only

- name: PackageInfo.g Dependencies.GAP
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "^  GAP := "
    line: '  GAP := ">= 4.12.0",'

- name: init.g header
  replace:
    path: "{{ pkg_dir }}/{{ package.path }}/init.g"
    regexp: "\\A(.*\n){5}"
    replace: |
      # SPDX-License-Identifier: GPL-2.0-or-later
      # {{ package.name }}: {{ package.description }}
      #
      # Reading the declaration part of the package.
      #
  when: not package.docu_only

- name: read.g header
  replace:
    path: "{{ pkg_dir }}/{{ package.path }}/read.g"
    regexp: "\\A(.*\n){5}"
    replace: |
      # SPDX-License-Identifier: GPL-2.0-or-later
      # {{ package.name }}: {{ package.description }}
      #
      # Reading the implementation part of the package.
      #
  when: not package.docu_only

- name: PackageInfo.g header
  replace:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "\\A(.*\n){8}"
    replace: |
      # SPDX-License-Identifier: GPL-2.0-or-later
      # {{ package.name }}: {{ package.description }}
      #
      # This file contains package meta data. For additional information on
      # the meaning and correct usage of these fields, please consult the
      # manual of the "Example" package as well as the comments in its
      # PackageInfo.g file.
      #
  when: not package.docu_only

- name: "Declaration headers"
  replace:
    path: "{{ cur_path }}"
    regexp: "\\A(.*\n){5}"
    replace: |
      # SPDX-License-Identifier: GPL-2.0-or-later
      # {{ package.name }}: {{ package.description }}
      #
      # Declarations
      #
  with_fileglob: "{{ pkg_dir }}/{{ package.path }}/gap/*.gd"
  loop_control:
    loop_var: cur_path
  when: not package.docu_only

- name: "Implementation headers"
  replace:
    path: "{{ cur_path }}"
    regexp: "\\A(.*\n){5}"
    replace: |
      # SPDX-License-Identifier: GPL-2.0-or-later
      # {{ package.name }}: {{ package.description }}
      #
      # Implementations
      #
  with_fileglob: "{{ pkg_dir }}/{{ package.path }}/gap/*.gi"
  loop_control:
    loop_var: cur_path
  when: not package.docu_only

- name: "Ensure {{ pkg_dir }}/{{ package.path }}/tst/ exists"
  file:
    path: "{{ pkg_dir }}/{{ package.path }}/tst/"
    state: directory
  when: not package.docu_only

- name: Remove 000_LoadPackage.tst
  file:
    path: "{{ pkg_dir }}/{{ package.path }}/tst/000_LoadPackage.tst"
    state: absent
  when: not package.docu_only

- name: 100_LoadPackage.tst
  template:
    src: 100_LoadPackage.tst.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/tst/100_LoadPackage.tst"
  vars:
    # load additional packages before package, so suggested dependencies can be loaded manually
    tests_packages_to_load: "{{ (package.tests_additional_packages_to_load | default([])) + [ package.name ] }}"
  when: not package.docu_only

- name: LICENSE
  copy:
    src: LICENSE
    dest: "{{ pkg_dir }}/{{ package.path }}/LICENSE"
  when: not package.docu_only

- name: Remove COPYING
  file:
    path: "{{ pkg_dir }}/{{ package.path }}/COPYING"
    state: absent
  when: not package.docu_only

- name: makedoc.g
  template:
    src: makedoc.g.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/makedoc.g"
    trim_blocks: false
  when: not package.docu_only

- name: makedoc_with_overfull_hbox_warnings.g
  template:
    src: makedoc_with_overfull_hbox_warnings.g.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/makedoc_with_overfull_hbox_warnings.g"
    trim_blocks: false
  when: not package.docu_only

- name: "Ensure {{ pkg_dir }}/{{ package.path }}/doc/ exists"
  file:
    path: "{{ pkg_dir }}/{{ package.path }}/doc/"
    state: directory
  when: not package.docu_only

- name: Doc.autodoc
  copy:
    src: Doc.autodoc
    dest: "{{ pkg_dir }}/{{ package.path }}/doc/Doc.autodoc"
    force: no
  when: not package.docu_only and not package.GAPDoc_docu

- name: clean
  template:
    src: clean.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/doc/clean"
    mode: a+x
  when: not package.docu_only

- name: Check if package has precompiled categories
  stat:
    path: "{{ pkg_dir }}/{{ package.path }}/gap/precompiled_categories/"
  register: precompiled_categories_dir

- name: Check if package has notebooks
  stat:
    path: "{{ pkg_dir }}/{{ package.path }}/examples/notebooks/"
  register: notebooks_dir

- name: Check if package has Makefile.in
  stat:
    path: "{{ pkg_dir }}/{{ package.path }}/Makefile.in"
  register: Makefile_in

- name: makefile
  template:
    src: makefile.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/makefile"
  vars:
    has_precompiled_categories: "{{ precompiled_categories_dir.stat.exists }}"
    has_notebooks: "{{ notebooks_dir.stat.exists }}"
  when: (not package.docu_only) and (not Makefile_in.stat.exists)

- name: testall.g
  template:
    src: testall.g.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/tst/testall.g"
  when: not package.docu_only

- name: testall_no_precompiled_code.g.j2
  template:
    src: testall_no_precompiled_code.g.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/tst/testall_no_precompiled_code.g"
  when: (not package.docu_only) and precompiled_categories_dir.stat.exists

- name: Remove testall_no_precompiled_code.g.j2
  file:
    path: "{{ pkg_dir }}/{{ package.path }}/tst/testall_no_precompiled_code.g"
    state: absent
  when: not ((not package.docu_only) and precompiled_categories_dir.stat.exists)

- name: PackageInfo.g TestFile
  lineinfile:
    path: "{{ pkg_dir }}/{{ package.path }}/PackageInfo.g"
    regexp: "TestFile := "
    line: 'TestFile := "tst/testall.g",'
  when: not package.docu_only

- name: Remove maketest.g
  file:
    path: "{{ pkg_dir }}/{{ package.path }}/maketest.g"
    state: absent
  when: not package.docu_only

- name: .gitignore
  template:
    src: .gitignore.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/.gitignore"
  when: not package.docu_only

- name: Notebooks binder link
  replace:
    path: "{{ cur_path }}"
    regexp: "\\A(.*\n){10}"
    replace: |
      {
       "cells": [
        {
         "cell_type": "markdown",
         "id": "5dd5d895",
         "metadata": {},
         "source": [
          "[![Binder](https://mybinder.org/badge_logo.svg)](https://gesis.mybinder.org/v2/gh/homalg-project/CapAndHomalgNotebooks/master?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fhomalg-project%252F{{ package.repo }}%26urlpath%3Dtree%252F{{ package.path | replace("/", "%252F") }}%252Fexamples%252F%252Fnotebooks%252F{{ cur_path | basename }}%26branch%3Dmaster)"
         ]
        },
  with_fileglob: "{{ pkg_dir }}/{{ package.path }}/examples/notebooks/*.ipynb"
  loop_control:
    loop_var: cur_path
  when: not package.docu_only

- name: .gitignore for notebooks
  copy:
    src: .gitignore_notebooks
    dest: "{{ pkg_dir }}/{{ package.path }}/examples/notebooks/.gitignore"
  when: notebooks_dir.stat.exists

- name: README.md for notebooks
  template:
    src: README.md_notebooks.j2
    dest: "{{ pkg_dir }}/{{ package.path }}/examples/notebooks/README.md"
  when: notebooks_dir.stat.exists
