- name: Set package variables for {{ package.name }}
  set_fact:
    package_name: "{{ package.name }}"
    project_name: "{{ package.target }}"
    package_description: "{{ package.description | default('') }}"
    target_path: ~/.julia/dev/{{ package.target }}
    source_package_path: "~/.gap/pkg/{{ package.source }}/{{ package.name }}"
    target_package_path: "~/.julia/dev/{{ package.target }}/{{ package.name }}"
    package_uuid: "{{ package.uuid | default('') }}"
    package_version: "{{ package.version | default('0.0.1') }}"
    julia_version: "{{ package.julia_version | default('1.11') }}"
    dependencies: "{{ package.dependencies | default({}) }}"
    weak_dependencies: "{{ package.weak_dependencies | default({}) }}"
    extras: "{{ package.extras | default([]) }}"
    targets: "{{ package.targets | default({'test': 'default'}) }}"
    disable_method_overwrite_warning: "{{ package.disable_method_overwrite_warning | default(false) }}"
    cleanup_test_files_by_keywords: "{{ package.cleanup_test_files_by_keywords | default([]) }}"
    playbook_dir_relative_to_home: "{{ playbook_dir | relpath(ansible_env.HOME) }}"

- name: Verify the GAP package {{ package_name }} exists
  stat:
    path: "{{ source_package_path }}"
  register: gap_package_directory_exists

- name: Fail if the GAP package {{ package_name }} does not exist
  fail:
    msg: "The GAP package directory '{{ source_package_path }}' does not exist!"
  when: not gap_package_directory_exists.stat.exists

- name: Run 'gap makedoc.g' in {{ source_package_path }} to update documentation silently
  command: gap -q -c 'makedoc.g > /dev/null 2>&1'
  args:
    chdir: '{{ source_package_path }}'
  register: makedoc_result
  changed_when: false

- name: Ensure the parent directory for the Julia package exists
  stat:
    path: "{{ target_path }}"
  register: target_path_exists

- name: Fail if the parent directory does not exist
  fail:
    msg: "The parent directory '{{ target_path }}' does not exist!"
  when: not target_path_exists.stat.exists

- name: Check whether the Julia package directory already exists
  stat:
    path: '{{ target_package_path }}'
  register: package_directory_exists

- name: Generate Julia package using Pkg.generate if it does not exist
  command: >
    julia -e "using Pkg; Pkg.generate(\"{{ package_name }}\")"
  args:
    chdir: '{{ target_path }}'
  when: package_directory_exists.stat.exists == false
  register: generate_julia_package

- name: Add LICENSE file to package
  copy:
    src: LICENSE
    dest: "{{ target_package_path }}/LICENSE"
    mode: '0644'
  when: package_directory_exists.stat.exists == false

- name: Add .gitignore file to package
  copy:
    src: gitignore
    dest: "{{ target_package_path }}/.gitignore"
    mode: '0644'

- name: Add {{ package_name }}.jl file to package
  template:
    src: package.jl.j2
    dest: "{{ target_package_path }}/src/{{ package_name }}.jl"
    mode: '0644'

- name: Add Makefile to package
  template:
    src: makefile.j2
    dest: "{{ target_package_path }}/makefile"
    mode: '0644'

- name: Add '.generate.sh' file to package
  template:
    src: generate.j2
    dest: "{{ target_package_path }}/.generate.sh"
    mode: '0755'

- name: Extract the package authors
  shell: gap -q -c '{{ display_authors_command }}'
  register: package_authors
  vars:
    display_authors_command: |
      Print(
        JoinStringsWithSeparator(
          List( PackageInfo("{{ package_name }}")[1].Persons,
            person -> Concatenation( "  \"", person.FirstNames, " ", person.LastName, " <", person.Email, ">\"")), ",\n"), "\n");
      QuitGap

- name: Extract the package verion in GAP
  shell: gap -q -c '{{ package_version_in_gap_command }}'
  register: package_version_in_gap
  vars:
    package_version_in_gap_command: |
      Print( PackageInfo("{{ package_name }}")[1].Version, "\n");
      QuitGap();

- name: Find the UUIDs of dependencies
  shell: |
    julia -e '
      using Pkg
      packages = {{ dependencies_names }}
      uuids = join(
        [name * " = \"" * string(uuid) * "\"" 
          for name in packages 
          for (uuid, package) in Pkg.dependencies() 
          if package.name == name
        ], 
        "\n"
      )
      println(uuids)
    '
  when: dependencies
  register: dependencies_uuids
  changed_when: false
  vars:
    dependencies_names: "{{ dependencies.keys() | list | to_json }}"

- name: Find the UUIDs of weak_dependencies
  shell: |
    julia -e '
      using Pkg
      packages = {{ weak_dependencies_names }}
      uuids = join(
        [name * " = \"" * string(uuid) * "\"" 
          for name in packages 
          for (uuid, package) in Pkg.dependencies() 
          if package.name == name
        ], 
        "\n"
      )
      println(uuids)
    '
  when: weak_dependencies
  register: weak_dependencies_uuids
  changed_when: false
  vars:
    weak_dependencies_names: "{{ weak_dependencies.keys() | list | to_json }}"

- name: Find the UUIDs of extras
  shell: |
    julia -e '
      using Pkg
      packages = {{ extras_names }}
      uuids = join(
        [name * " = \"" * string(uuid) * "\"" 
          for name in packages 
          for (uuid, package) in Pkg.dependencies() 
          if package.name == name
        ], 
        "\n"
      )
      println(uuids)
    '
  when: extras
  register: extras_uuids
  changed_when: false
  vars:
    extras_names: "{{ extras | to_json }}"

- name: Add Project.toml to package
  template:
    src: Project.toml.j2
    dest: "{{ target_package_path }}/Project.toml"
    mode: '0644'

- name: Add README.md to package
  template:
    src: README.md.j2
    dest: "{{ target_package_path }}/README.md"
    mode: '0644'

- name: Make sure the directory test exists
  file:
    path: "{{ target_package_path }}/test"
    state: directory
    mode: '0755'

- name: Make sure the directories src/gap, docs/src and test exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "{{ target_package_path }}/src"
    - "{{ target_package_path }}/src/gap"
    - "{{ target_package_path }}/docs"
    - "{{ target_package_path }}/docs/src"
    - "{{ target_package_path }}/test"

- name: List the names of all subdirectories in {{ source_package_path }}/gap
  find:
    paths: '{{ source_package_path }}/gap'
    file_type: directory
  register: gap_subdirs

- name: Make sure these directories exist in the Julia package
  file:
    path: "{{ target_package_path }}/src/gap/{{ item.path | basename }}"
    state: directory
  loop: '{{ gap_subdirs.files }}'

- name: Add runtests.jl in test directory
  template:
    src: runtests.jl.j2
    dest: "{{ target_package_path }}/test/runtests.jl"
    mode: '0644'

- name: Copy init.jl to src directory
  copy:
    src: init.jl
    dest: "{{ target_package_path }}/src/init.jl"
    mode: '0644'

- name: Copy read.g and init.g files into julia src directory
  copy:
    src: '{{ source_package_path }}/{{ item }}'
    dest: '{{ target_package_path }}/src/{{ item }}.autogen.jl'
    mode: '0644'
  with_items:
    - read.g
    - init.g

- name: Alter read- & init.g.autogen.jl files in-place
  shell: |
    sed -i \
      -e 's/ReadPackage/include/g' \
      -e 's/"{{ package_name }}"\s*,\s*//g' \
      -e 's/\.g\([di]\)"/.g\1.autogen.jl"/g' \
      {{ target_package_path }}/src/{{ item }}
  with_items:
    - read.g.autogen.jl
    - init.g.autogen.jl

- name: Transpile GAP code to Julia using the script transpile_gap_to_julia
  shell: '{{ playbook_dir }}/files/transpile_gap_to_julia {{ package_name }}'
  args:
    executable: /bin/bash
  register: transpile_result

- name: Find files in the docs/src
  find:
    paths: '{{ target_package_path }}/docs/src'
    patterns: '*.md'
  register: docs_src_files

- name: Filter the test files by keyswords
  shell: |
    grep -l -e "{{ cleanup_test_files_by_keywords | join('" -e "') }}" "{{ item.path }}" || true
  loop: '{{ docs_src_files.files }}'
  when: cleanup_test_files_by_keywords | length > 0
  register: matched_files
  changed_when: false

- name: Extract matching file paths
  set_fact:
    cleanup_test_files: '{{ matched_files.results | selectattr("stdout", "!=", "") | map(attribute="stdout") | list }}'

- name: Remove files that contain the keyword
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ cleanup_test_files }}"
  when: cleanup_test_files | length > 0
  register: removed_files

- name: Find AutoDocTest fragments
  find:
    paths: '{{ target_package_path }}/docs/src'
    patterns: '{{ package_name | lower }}*.tst.autogen.md'
  register: autodoctest_files

- name: Merge AutoDocTest fragments
  shell: |
    cat {{ autodoctest_files.files | map(attribute='path') | join(' ') }} > {{ target_package_path }}/docs/src/AutoDocTests.tst.autogen.md
  when: autodoctest_files.matched     
- name: Remove AutoDocTest fragments
  file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ autodoctest_files.files }}'
  when: autodoctest_files.matched > 0

- name: Execute tests in the same session
  shell: |
    sed -i 's/```jldoctest/```jldoctest AutoDocTests/g' {{ target_package_path }}/docs/src/AutoDocTests.tst.autogen.md

- name: debug
  debug:
    msg: "{{ autodoctest_files.files | map(attribute='path') | list }}"

- name: Display success message
  debug:
    msg: "Julia package '{{ package_name }}' created/updated in '{{ target_path }}'"