julia_packages:
  - package_name: ToolsForCategoricalTowers
    project_name: CategoricalTowers.jl
    package_description: Tools for CategoricalTowers
    package_uuid: e2cf920d-0824-4cbb-97bb-0be40824f89f
    package_version: 0.0.1
    julia_version: 1.11
    dependencies:
      CAP: 0.6
      MonoidalCategories:
      CartesianCategories:
    weak_dependencies:
    extras:
      - Documenter
      - Test
      - Toposes
      - FinSetsForCAP
      - MatricesForHomalg
      - FreydCategoriesForCAP
    targets:
      test: default
    disable_method_overwrite_warning: true
    cleanup_test_files_by_keywords:
      - drop_example_in_Julia
  - package_name: QuotientCategories
    project_name: CategoricalTowers.jl
    package_description: Quotient categories for CAP
    package_uuid: c103c924-3523-4680-a691-c88f3312ec70
    package_version: 0.0.1
    julia_version: 1.11
    dependencies:
      CAP: 0.6
      ToolsForCategoricalTowers:
      MatricesForHomalg:
    weak_dependencies:
    extras:
      - Documenter
      - Test
      - FreydCategoriesForCAP
    targets:
      test: default
    disable_method_overwrite_warning: true
    cleanup_test_files_by_keywords:
      - drop_example_in_Julia
  - package_name: FpCategories
    project_name: CategoricalTowers.jl
    package_description: Finitely presented categories by generating quivers and relations
    package_uuid: b9f20f1b-1226-4811-b6a0-b2e47a225553
    package_version: 0.0.1
    julia_version: 1.11
    dependencies:
      CAP: 0.6
      CartesianCategories:
      ToolsForCategoricalTowers:
      QuotientCategories:
      FinSetsForCAP:
    weak_dependencies:
    extras:
      - Documenter
      - Test
    targets:
      test: default
    disable_method_overwrite_warning: true
    cleanup_test_files_by_keywords:
      - drop_example_in_Julia
      - Algebroids
